Repository AlmaLinux/almalinux.org, pull requests merged in 2023-08, with the labels that each got.

#295 Added a blog post call for testers for security updates
  content/blog/testers-needed-for-updated-packages-intel-and-amd-cpus-affected.md
  static/blog-images/testers-post.png
Labels: Staged

#302 Collection of updates
  assets/css/bundle.css
  layouts/index.html
  layouts/members/single.html
  static/brands/AlmaCarePoweredByTuxCare.svg
Labels: enhancement

#306 Replaced the TuxCare logo to the correct one
  layouts/index.html
  static/brands/Final_Horizontal_Logo_WithTagLine_White.svg
Labels: bug

#297 Border-bottom fix and fixed text in Features section
  assets/css/bundle.css
  i18n/en.json
  layouts/index.html
Labels: enhancement

#254 Separate page for AlmaLinux downloads
  assets/css/bundle.css
  content/get-almalinux.md
  i18n/en.json
  layouts/get-almalinux/single.html
  layouts/index.html
  layouts/partials/common/footer.html
  layouts/partials/common/nav.html
Labels: enhancement
