Repository AlmaLinux/almalinux.org, pull requests merged in 2024-05, with the labels that each got.

#533 Fixed a typo that was causing a translation error.
  i18n/en.json
  layouts/get-almalinux/single.html
Labels: bug

#532 Blog Introducing the AlmaLinux HPC and AI SIG
  content/blog/2024-05-02-introducing-almalinux-hpc-ai-sig.md
  static/blog-images/2024/introducing-almalinux-hpc-ai-sig.png
  static/users/haydenbarnes.jpg
Labels: Staged, blog post

#558 Added third Secure Boot Certificate
  i18n/en.json
  layouts/security/single.html
Labels: enhancement

#548 Updated Generic Cloud and OpenNebula links
  layouts/get-almalinux/single.html
Labels: enhancement

#565 adding a blog post for promoting the azure webinar
  content/blog/2024-05-23-mythbusting-linux-on-azure.md
  static/blog-images/2024/azurewebinar.png
Labels: blog post

#569 8.10 release
  content/blog/2024-05-28-announcing-810-stable.md
  static/blog-images/2024/2024-05-28-almalinux-8-10-stable.png
Labels: blog post

#568 Added YouTube shortcode width and height functionality
  content/blog/2023-12-14-2023-highlights.md
  content/blog/2024-01-16-video-contributions.md
  content/blog/2024-02-01-aldt-recap.md
  content/blog/2024-02-29-feb-event-recap.md
  content/blog/2024-05-01-almalinux-day-germany-recap.md
  content/blog/2024-05-06-announcing-94-stable.md
  contributing-blog-posts.md
  layouts/shortcodes/youtube.html
Labels: bug, enhancement
