Repository AlmaLinux/almalinux.org, pull requests merged in 2024-10, with the labels that each got.

#648 Fixed deprecated warnings
  config.yaml
  layouts/blog/single.html
  layouts/partials/common/opengraph.html
Labels: bug

#623 Added FIPS blog post
  content/blog/2024-10-07-fips-validation-for-almalinux-update.md
  static/blog-images/2024/fipsupdate.png
  static/blog-images/2024/nmap-fips.png
  static/blog-images/2024/nmap-nonfips.png
Labels: Staged, blog post

#613 Added sponsorship levels to commercial support section.
  assets/css/bundle.css
  layouts/index.html
Labels: enhancement
